version: "3"
services:
  server:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/midelight
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules

  mongo:
    image: mongo:latest
    volumes:
      - ./mongo-data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo-data:
  node_modules: